# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a5c67e03254ece5ee4ff12f3e84fb65629e6c1313898cf19e2cdaaa9f6a4a749c8b6e9264039ac3095786982eb0cc7e0543b0a921a97901d923cdd4506b6050

test:
  secret_key_base: 817242ea5850c12c0fca03c361dd087f5fe74cd8c314a854c455aecbd62170b787295b345922c31601b72887f54e3b97f6922b32940f567a176231c1f874c966

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
